let sb;
const $=id=>document.getElementById(id);
function client(){if(!sb){if(typeof SUPABASE_URL==="undefined"||typeof SUPABASE_ANON_KEY==="undefined")throw Error("config.js belum berisi konfigurasi Supabase");sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY)}return sb}
function msg(id,t,bad=false){$(id).textContent=t||"";$(id).style.color=bad?"#b00020":"#16723a"}
async function init(){try{const {data}=await client().auth.getSession();if(data.session)showDash()}catch(e){msg("loginMessage",e.message,true)}}
function showDash(){$("loginBox").hidden=true;$("dashboard").hidden=false;load()}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();msg("loginMessage","Memproses...");try{const {error}=await client().auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)throw error;showDash()}catch(e){msg("loginMessage",e.message,true)}})
$("logoutBtn").addEventListener("click",async()=>{await client().auth.signOut();location.reload()})
$("productImage").addEventListener("change",()=>{const f=$("productImage").files[0];if(!f){$("previewBox").hidden=true;return}$("previewImage").src=URL.createObjectURL(f);$("previewBox").hidden=false})
$("productForm").addEventListener("submit",async e=>{e.preventDefault();const f=$("productImage").files[0],d=$("description").value.trim();if(!f||!d)return msg("uploadMessage","Gambar dan deskripsi wajib diisi.",true);const btn=$("uploadBtn");btn.disabled=true;btn.textContent="Mengupload...";try{const name=Date.now()+"-"+f.name.toLowerCase().replace(/[^a-z0-9.]+/g,"-");let r=await client().storage.from("Produk").upload(name,f,{cacheControl:"3600",upsert:false});if(r.error)throw r.error;const {data:u}=client().storage.from("Produk").getPublicUrl(name);r=await client().from("produk").insert({gambar:u.publicUrl,deskripsi:d});if(r.error){await client().storage.from("Produk").remove([name]);throw r.error}$("productForm").reset();$("previewBox").hidden=true;msg("uploadMessage","Produk berhasil ditambahkan.");load()}catch(e){msg("uploadMessage",e.message,true)}finally{btn.disabled=false;btn.textContent="Upload Produk"}})
async function load(){const grid=$("productsGrid");grid.innerHTML="<p>Memuat...</p>";try{const {data,error}=await client().from("produk").select("*").order("created_at",{ascending:false});if(error)throw error;grid.innerHTML="";$("emptyMessage").hidden=!!data.length;data.forEach(x=>{const c=document.createElement("article");c.className="product";c.innerHTML='<img loading="lazy"><div class="body"><p></p><button class="delete">Hapus Produk</button></div>';c.querySelector("img").src=x.gambar;c.querySelector("p").textContent=x.deskripsi;c.querySelector(".delete").onclick=()=>del(x);grid.appendChild(c)})}catch(e){grid.innerHTML="";msg("uploadMessage",e.message,true)}}
async function del(x){if(!confirm("Yakin ingin menghapus produk ini?"))return;try{let r=await client().from("produk").delete().eq("id",x.id);if(r.error)throw r.error;const marker="/storage/v1/object/public/Produk/";const i=x.gambar.indexOf(marker);if(i>=0)await client().storage.from("Produk").remove([decodeURIComponent(x.gambar.slice(i+marker.length))]);load()}catch(e){alert("Gagal menghapus: "+e.message)}}
$("refreshBtn").onclick=load;init();